# Generated by Django 5.0.3 on 2024-03-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagtype',
            options={'ordering': ['name'], 'verbose_name': 'bag type', 'verbose_name_plural': 'bag types'},
        ),
        migrations.AddField(
            model_name='bagtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bagtype',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
            preserve_default=False,
        ),
    ]
