# Generated by Django 4.1.2 on 2022-11-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='max_luggage_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
