# Generated by Django 5.0.3 on 2024-03-09 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0002_alter_bagtype_options_bagtype_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['created'], 'verbose_name': 'bus', 'verbose_name_plural': 'buses'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['fullname'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='luggage',
            options={'ordering': ['-created'], 'verbose_name': 'luggage', 'verbose_name_plural': 'luggages'},
        ),
        migrations.AlterModelOptions(
            name='luggagebill',
            options={'ordering': ['-created'], 'verbose_name': 'luggage bill', 'verbose_name_plural': 'luggage bills'},
        ),
        migrations.AlterModelOptions(
            name='parklocation',
            options={'ordering': ['state'], 'verbose_name': 'park location', 'verbose_name_plural': 'park locations'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['created'], 'verbose_name': 'state', 'verbose_name_plural': 'states'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['created'], 'verbose_name': 'weight', 'verbose_name_plural': 'weights'},
        ),
        migrations.AlterField(
            model_name='bagtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bagtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='bagtype',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(max_length=150, verbose_name="Driver's name"),
        ),
        migrations.AlterField(
            model_name='bus',
            name='max_luggage_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum luggage weight'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='plate number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fullname',
            field=models.CharField(max_length=150, unique=True, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='next_of_kin',
            field=models.CharField(max_length=150, verbose_name='next of kin'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='next_of_kin_phonenumber',
            field=models.CharField(max_length=11, verbose_name='next of kin phonenumber'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='bag_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.bagtype', verbose_name='bag type'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='luggage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='luggages.luggagebill', verbose_name='luggage'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.weight', verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='luggagebill',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='added by'),
        ),
        migrations.AlterField(
            model_name='luggagebill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='luggagebill',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.trip', verbose_name='trip'),
        ),
        migrations.AlterField(
            model_name='parklocation',
            name='contact',
            field=models.TextField(verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='parklocation',
            name='full_address',
            field=models.CharField(max_length=255, verbose_name='full address'),
        ),
        migrations.AlterField(
            model_name='parklocation',
            name='location',
            field=models.CharField(max_length=50, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='parklocation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.state', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='state',
            name='short_code',
            field=models.CharField(max_length=3, verbose_name='short code'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.bus', verbose_name='bus'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_of_journey',
            field=models.DateTimeField(verbose_name='date of journey'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='luggages.state', verbose_name='departure'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='luggages.state', verbose_name='destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(help_text='format: ENU-to-LAG-01-01-2000', max_length=50, unique=True, verbose_name='trip'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='min_weight',
            field=models.PositiveIntegerField(verbose_name='minimum weight'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
    ]
