# Generated by Django 4.1.2 on 2022-11-06 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0002_bus_max_luggage_weight_alter_trip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_of_journey',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
