# Generated by Django 5.0.3 on 2024-03-23 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0003_alter_bus_options_alter_customer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagtype',
            options={'ordering': ['name'], 'verbose_name': 'Bag Type', 'verbose_name_plural': 'Bag Types'},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['created'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['fullname'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='luggage',
            options={'ordering': ['-created'], 'verbose_name': 'Luggage', 'verbose_name_plural': 'Luggages'},
        ),
        migrations.AlterModelOptions(
            name='luggagebill',
            options={'ordering': ['-created'], 'verbose_name': 'Luggage Bill', 'verbose_name_plural': 'Luggage Bills'},
        ),
        migrations.AlterModelOptions(
            name='parklocation',
            options={'ordering': ['state'], 'verbose_name': 'Park Location', 'verbose_name_plural': 'Park Locations'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['created'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['created'], 'verbose_name': 'Weight', 'verbose_name_plural': 'Weights'},
        ),
        migrations.AlterField(
            model_name='bagtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bagtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bagtype',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(max_length=150, verbose_name="Driver's Name"),
        ),
        migrations.AlterField(
            model_name='bus',
            name='max_luggage_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Luggage Weight'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Plate Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fullname',
            field=models.CharField(help_text='Full name of the customer.', max_length=150, unique=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='next_of_kin',
            field=models.CharField(max_length=150, verbose_name='Next of Kin'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='next_of_kin_phonenumber',
            field=models.CharField(max_length=11, verbose_name='Next of Kin Phone Number'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='bag_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.bagtype', verbose_name='Bag Type'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='luggage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='luggages.luggagebill', verbose_name='Luggage'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.weight', verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='luggagebill',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='luggagebill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='luggagebill',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggagebills', to='luggages.trip', verbose_name='Trip'),
        ),
        migrations.AlterField(
            model_name='parklocation',
            name='contact',
            field=models.TextField(verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='parklocation',
            name='full_address',
            field=models.CharField(max_length=255, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='parklocation',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='parklocation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='state',
            name='short_code',
            field=models.CharField(max_length=3, verbose_name='Short Code'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggages.bus', verbose_name='Bus'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_of_journey',
            field=models.DateTimeField(verbose_name='Date of Journey'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='luggages.state', verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='luggages.state', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(help_text='Format: EN-to-LA-01-01-2000', max_length=50, unique=True, verbose_name='Trip'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='min_weight',
            field=models.PositiveIntegerField(verbose_name='Minimum Weight'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
