# Generated by Django 4.1.2 on 2022-12-29 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('luggages', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggagebill',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fullname',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='next_of_kin',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(help_text='format: ENU-to-LAG-01-01-2000', max_length=50, unique=True),
        ),
    ]
