# Generated by Django 5.0.3 on 2024-03-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0006_luggagebill_added_by_alter_bus_driver_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
