# Generated by Django 5.0.4 on 2024-05-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0007_alter_bus_plate_number_alter_parklocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(help_text='Format: ENU-to-LAG-01-01-2000', max_length=50, unique=True, verbose_name='Trip'),
        ),
    ]
