# Generated by Django 5.0.4 on 2024-05-01 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0008_alter_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='next_of_kin_phonenumber',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must start with 0803, 0806, 0809, 0703, 0706, 0709, 0813, 0816, or 0819 and be 11 digits long.', regex='^(0803|0806|0809|0703|0706|0709|0813|0816|0819)\\d{7}$')], verbose_name='Next of Kin Phone Number'),
        ),
    ]
