# Generated by Django 5.0.4 on 2024-05-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0009_alter_customer_next_of_kin_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='luggages.parklocation', verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='luggages.parklocation', verbose_name='Destination'),
        ),
    ]
