# Generated by Django 5.0.4 on 2024-05-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0010_alter_trip_departure_alter_trip_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='short_code',
            field=models.CharField(help_text='3-letter state shortcode.', max_length=3, verbose_name='Short Code'),
        ),
    ]
