# Generated by Django 5.0.4 on 2024-05-01 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0011_alter_state_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='plate_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Plate number must be in the format: AAA-111-AAA', regex='^[A-Z]{3}-\\d{3}-[A-Z]{3}$')], verbose_name='Plate Number'),
        ),
    ]
