# Generated by Django 5.0.4 on 2024-05-01 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0013_alter_bus_max_luggage_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='min_weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Weight'),
        ),
    ]
