# Generated by Django 5.0.4 on 2024-05-01 09:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0014_alter_weight_min_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price'),
        ),
    ]
