# Generated by Django 5.0.4 on 2024-05-01 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0015_alter_weight_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luggage',
            name='luggage',
        ),
        migrations.AddField(
            model_name='luggage',
            name='luggagebill',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='luggages.luggagebill', verbose_name='Luggage Bill'),
            preserve_default=False,
        ),
    ]
