# Generated by Django 5.0.4 on 2024-05-01 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggages', '0016_remove_luggage_luggage_luggage_luggagebill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
    ]
